### ISSUE TITLE
[ECOSYSTEM CHALLENGE] Using Remix And MetaMask On Moonbeam

### ISSUE THREAD

**Issue by albertov19** [vinhbhn/Moonbeam#2]
Hi vibhbhn,

Thank you for your submission in our Moonbeam challenge. Unfortunately, the allowance is not correctly set in your ERC20 token. Remember that following the challenge instructions, you need to allow a specific address so it can make a transfer. For that you can use Remix and the "approve" method, and you can check it with the "allowance" call.

Regards,
Alberto

**Comment by vinhbhn** [comment]
Thanks for reminding. I have just updated 2 moonbeam projects.

**Comment by albertov19** [comment]
Hi @vinhbhn,

I'm still having issues with the allowance. Also note that you have to account for the decimal places when approving the spender. So if your token has 3 decimals places (for example) and you want to approve that address for 10 tokens, you need to pass in 10000.

Regards
Alberto

**Comment by vinhbhn** [comment]
I just updated again

**Comment by albertov19** [comment]
Hi @vinhbhn,

I'm still having issues, feel free to reach out to me in Discord and I'll help you out.

Regards
Alberto
